import express from "express";
import jwt from "jsonwebtoken";
import userModel from "../models/user.js";// in es6 modules you need to mention extention .js etc.
import authenticate from "../middleware/authenticate.js";
import dotenv from "dotenv"
import bcrypt from "bcryptjs";// to convert passwords into hashtrings which are oneway only to maintain secrecy.


dotenv.config();
const app = express();

app.use(express.json())// if we dont put this middleware then data doesnt come in req.body


app.get("/api",(req, res)=>{
    res.status(200).json({
        message: "welcome to the authentication api"
    })
})

app.post("/api/auth/register", async (req, res)=>{
    const {email, name, password} = req.body;

    const user = await userModel.create({
        email, name, password: await bcrypt.hash(password, 10)
    })
    const token = jwt.sign(
        {
            id: user._id
        },
        process.env.JWT_SECRET// remember the jwt secret never goes inside the token or included in token.
        // above jwt secret is to find whether this current token was generated by this/our server in past or not.
    )

    res.status(200).json({
        message: "user created successfully",
        data:{
            user:{
              id:  user._id
            }, token
        }
    })
})

app.get("/api/auth/me", authenticate ,async (req, res)=>{
    console.log(req.user);
    res.status(200).json({
        data:{
            user: req.user
        }
    }
    )
})

app.post("/api/auth/login", async (req, res)=>{
    const {email, password} = req.body
    const user = await userModel.findOne({
        email
    })

    const isValidPassword = bcrypt.compare(password, user.password);
    if(!isValidPassword){
        return res.status(400).json({
            message: "invalid password or email"
        })
    }

    const token = jwt.sign({
        id: user._id
    }, process.env.JWT_SECRET)
    res.status(200).json({
        message: "user logged in",
        data:{
            user: {
                email: user.email,
                name: user.name
            }
        },
        token
    })
})

export default app
