import {Router} from "express"
import userModel from "../models/user.model.js"
import bcrypt from "bcryptjs"
import {verifyRefreshToken, generateTokens, verifyAccessToken } from "../utils/auth.js"



const router = Router()

router.post("/register", async (req, res)=>{
    const {name, email, password} = req.body

    const isUserExists = await userModel.findOne({email:email})// we need to give only an object inside findOne() as an argument. 
    if(isUserExists){
        return res.status(400).json({
            message: "user already exists",
            errors:[
                {
                    field: "email",
                    message: "user already exists"
                }
            ]
        })
    }

    const user = await userModel.create({
        name,email,passwordHash:await bcrypt.hash(password, 10)
    })

    const {accessToken, refreshToken} = generateTokens({userId: user._id})
    res.cookie("refreshToken", refreshToken,{
        httpOnly: true, // so that client side js won't be able to access cookie.
    })

    user.refreshToken = refreshToken
   
    await user.save();

    res.status(201).json({
        message: "user registered successfully",
        data: {
            user:{
                name: user.name,
                email: user.email,
            } 
        },accessToken
    })
})

router.get("/me", async (req, res)=>{
    const accessToken = req.headers.authorization?.split(" ")[1]

    try{
        const decoded = verifyAccessToken(accessToken)
        const user = await userModel.findById(decoded.id)
        res.status(200).json({
            message: "user fetched successfully",
            data:{
                user:{
                    name: user.name,
                    email: user.email
                }
            }
        })
    }
    catch(error){
        return res.status(401).json({
            message: "unauthorized, invalid or expired access token",
        })
    }
}) 

router.post("/refresh", async (req, res)=>{
    const refreshToken = req.cookies.refreshToken

    if(!refreshToken){
        return res.status(401).json({
            message: "unauthorzed, refresh token not found",
        })
    }

    try{
       const decoded = verifyRefreshToken(refreshToken)
       const user = await userModel.findById(decoded.id)

       if(refreshToken !== user.refreshToken){
        user.refreshToken = null
        await user.save();
        return res.status(401).json({
            message: "unauthorized, refresh token mismatch",
        })
       } 

       const {accessToken, refreshToken: newRefreshToken}= generateTokens({userId: user._id})// here only for a moment we gave the reftoken generated by gt a newRefreshToken name so it gets stored in same
       res.cookie("refreshToken", newRefreshToken, {httpOnly: true})// refreshToken key of database etc, because above we have already used the key name refreshtoken for cookies....
       user.refreshToken = newRefreshToken
       await user.save()// directly interacts with database
       res.status(200).json({
        message: " tokens refreshed successfully",
        accessToken
       })

    }
    catch(error){
        return res.status(401).json({
            message: "unauthorized, invalid or expired refresh Token",
        })
    }
})

export default router